# site settings
title: NoPad
subtitle: by Erblocker
email: chainsx@outlook.com
description: NoPad计划是由DiXin_Ren的构想，cgoxopx在Erblocker里提出，chainsx进行实现的<br /> 一个关于改善云课堂教学模式的计划，其提供了关于修复破解睿易派/少年派的解决方案，我们希望睿易云越办越好。
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: ""
author:
street_address: github
city: Erblocker
state: chainsx
zip_code: dixin_ren
country: YRSSF&Pandora-magicbox
phone: chainsx@outlook.com

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/Erblocker
gitlab_url: https://gitlab.com/chainsx
googleplus_url: https://plus.google.com/u/0/+pzhrhlx
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
